server:
  port: 8090
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3306/ADOBE_MAY_24?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Welcome123
    jpa:
      hibernate.ddl-auto: update
      properties:
        hibernate:
          format_sql:true
          dialect:org.hibernate.dialect.MySQLDialect
